import { NextResponse } from "next/server";
import { GoogleGenerativeAI } from "@google/generative-ai";

const FALLBACK_RESPONSE = `AI Credit Memo: Initial Draft
Date: ${new Date().toLocaleDateString()}
Generated by: FinServe AI Copilot (Gemini 3.1 Flash-Lite)

1. Executive Summary
The applicant demonstrates a solid core business model with strong recurring revenue and a history of steady debt service. However, recent macroeconomic factors have caused mild margin compression, requiring careful monitoring. The requested loan purpose is clearly defined and aimed at revenue-generating CapEx/Expansion. 

2. Strengths & Mitigants
- Strong Debt Service: The DSCR is comfortable, indicating sufficient cash flow to cover both existing obligations and the proposed facility.
- Management Competence: Proven historical operating history with deep ties to local markets and suppliers.
- Collateral Adequacy: The LTV constraints are met aggressively, offering FinServe strong recovery options in a downside scenario.

3. Key Risk Factors
- Macro Variables: Vulnerability to shifts in supply chain pricing or raw material costs.
- Concentration Risk: Revenue is somewhat dependent on a concentrated vendor or client base.
- Leverage Post-Close: The addition of this facility will elevate the overall global leverage profile temporally until new revenue is realized.

4. Financial Health Assessment
Overall financial health is Adequate/Satisfactory. The balance sheet reflects controlled leverage, and the income statement proves that EBITDA can support the new debt schedule. Legal and compliance red flags are either minimal or mitigated.

5. Final Recommendation
Based on the synthesis of the CRM context and financial matrices, the preliminary AI recommendation is to PROCEED TO APPROVAL with standard financial covenants attached.

Note to Credit Officer: Please review this drafted justification, adjust the risk factors where necessary based on manual overrides, and click 'Route to Committee' when finalized.`;

const SYSTEM_PROMPT = `You are a Senior Credit Risk Officer at FinServe.
Your job is to analyze the provided applicant CRM context, financial metrics (EBITDA, Net Income, etc.), and calculate the risk based on DSCR and LTV. 
You MUST output a detailed credit memo in PLAIN TEXT. 
DO NOT use any markdown formatting whatsoever. DO NOT use asterisks (*) or hashes (#) to format text, not even for bolding. Use clean paragraph breaks and standard numbered lists.

Structure your plain text output strictly as follows:
AI Credit Memo: Initial Draft
Date: [Current Date]
Generated by: FinServe AI Copilot

1. Executive Summary
[1-2 paragraphs synthesizing their overall business context, loan purpose, and viability]

2. Strengths & Mitigants
- [Bullet points drawn directly from the context/financials]

3. Key Risk Factors
- [Bullet points drawn directly from context/financials]

4. Financial Health Assessment
[A robust analysis of their EBITDA, debt coverage ratio (DSCR), and legal/KYC standing]

5. Final Recommendation
[Clear statement: APPROVE, REJECT, or ESCALATE TO REVIEW]

Do not include any other conversational text. Just the plain text memo.`;

/**
 * API Route: POST /api/generate-memo
 * 
 * Generates an initially drafted Credit Memo by synthesizing raw CRM and financial 
 * profile data via the Google Gemini AI Model.
 * 
 * Enterprise Logic Highlights:
 * 1. Prompt Construction: The system prompt tightly binds Gemini 
 *    into a "Strict Financial Analyst" persona. It explicitly blocks formatting 
 *    symbols (*, #) to ensure the plain text output flows seamlessly into the 
 *    human-in-the-loop <textarea> workspace for analyst override.
 * 2. Fallback Architecture: If the GEMINI_API_KEY is omitted or a rate limit occurs, 
 *    the handler gracefully mimics network latency and serves a hardcoded Fallback 
 *    Response string to maintain continuous demo integrity.
 * 
 * @param {Request} req - The standard incoming App Router POST request.
 *    Expected JSON Payload: { context, companyName, requestedAmount, financials }
 * @returns {NextResponse} Returns JSON -> { memoHtml: string }
 */
export async function POST(req: Request) {
  try {
    const { context, companyName, requestedAmount, financials } = await req.json();

    if (!context) {
      return NextResponse.json({ error: "Context is required" }, { status: 400 });
    }

    const apiKey = process.env.GEMINI_API_KEY;

    // Fallback if no API key is provided
    if (!apiKey) {
      console.warn("No GEMINI_API_KEY found. Falling back to mock data...");
      await new Promise(resolve => setTimeout(resolve, 2500));
      return NextResponse.json({ memoHtml: FALLBACK_RESPONSE });
    }

    const genAI = new GoogleGenerativeAI(apiKey);
    const model = genAI.getGenerativeModel({ model: "gemini-3.1-flash-lite-preview" });

    const fullPrompt = `${SYSTEM_PROMPT}\n\n[Applicant: ${companyName}]\n[Requested: ${requestedAmount}]\n[Financials: ${JSON.stringify(financials)}]\n\nApplicant Context:\n${context}`;

    const result = await model.generateContent({
      contents: [
        { role: "user", parts: [{ text: fullPrompt }] }
      ],
      generationConfig: {
        responseMimeType: "text/plain", // Changing to plain text markdown for drafting
      }
    });

    const text = result.response.text();

    return NextResponse.json({ memoHtml: text });

  } catch (error) {
    console.error("Error generating memo:", error);
    // Fallback on any API failure
    await new Promise(resolve => setTimeout(resolve, 2500));
    return NextResponse.json({ memoHtml: FALLBACK_RESPONSE });
  }
}
